Get http://localhost:3000/api/todos/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWFmNGRlNjhiMmZmMDI0YWEyODc2OCIsImlhdCI6MTc0NjU5NzY3MSwiZXhwIjoxNzQ2NjAxMjcxfQ.OzCqNJXWdK1VBHLW38jn3QsmWDoB-n5igX7GLU1R-1w
###
DELETE http://localhost:3000/api/todos/list/681b03f4b2563b66a71f7ecc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWFmNGRlNjhiMmZmMDI0YWEyODc2OCIsImlhdCI6MTc0NjYwMDk2MCwiZXhwIjoxNzQ2NjA0NTYwfQ.nJXvCxGhkDjdXbYmLkagMNLoysIteFDZ7uxk6Qa3tfM

###

put http://localhost:3000/api/todos/list/681b03f4b2563b66a71f7ecc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWFlMWUwNjI2MTRiYTY0Y2RiMzcwYyIsImlhdCI6MTc0NjYwMTI1OSwiZXhwIjoxNzQ2NjA0ODU5fQ.Us9NeHyir5vxqZj7Gby0z1-CNQ7kqcg3bD680uEmEQU

{
  "title": "Test Updated List from owner"
}

###


POST http://localhost:3000/api/todos/list/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWFlMWUwNjI2MTRiYTY0Y2RiMzcwYyIsImlhdCI6MTc0NjYwNTcxMSwiZXhwIjoxNzQ2NjA5MzExfQ.8B2t70oucgyI4ZiHcbfd43WjW-CJJSO0HwMee1_9SEs

{
  "title": "List2"
}


###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "TestUser3",
  "email": "Test3@test.com",
  "password": "Test1234"
}
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "Test@test.com",
  "password": "Test1234"
}