Get http://localhost:3000/api/tasks/681b17574c7fc7d775bcc544
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWJkYzFjMDVkMjI5MDUzZjE0MmMwOCIsImlhdCI6MTc0NjY1NjI4OSwiZXhwIjoxNzQ2NjU5ODg5fQ.OtMdytkZpKGw1t0g1D3C-ChGeNV6lCVjc3-b5nyryZA

###

Post http://localhost:3000/api/tasks/681b17574c7fc7d775bcc544/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWFlMWUwNjI2MTRiYTY0Y2RiMzcwYyIsImlhdCI6MTc0NjYxMzg5NywiZXhwIjoxNzQ2NjE3NDk3fQ.u1LRf4uvSvb2Xuc8Tt8tFKaosYco87iZ-4wLOPbRfRE

{
    "title": "Task6",
    "description": "New Task from TestUser"
}

###

PUT http://localhost:3000/api/tasks/681b17574c7fc7d775bcc544/681b17734c7fc7d775bcc54a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWFlMWUwNjI2MTRiYTY0Y2RiMzcwYyIsImlhdCI6MTc0NjYxMTg1MywiZXhwIjoxNzQ2NjE1NDUzfQ.vy2eMkOpIXZbWbxoaaxRzscClfqD6rz4m0Z-iXpVBD0

{
    "title": "updated2 task",
    "description": "New Task from TestUser"
}

###

DELETE http://localhost:3000/api/tasks/681b17574c7fc7d775bcc544/681b34c63b0fbb0a1be82414
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWFlMWUwNjI2MTRiYTY0Y2RiMzcwYyIsImlhdCI6MTc0NjYxMTg1MywiZXhwIjoxNzQ2NjE1NDUzfQ.vy2eMkOpIXZbWbxoaaxRzscClfqD6rz4m0Z-iXpVBD0
