Post http://localhost:3000/api/shared/share-list/681b17574c7fc7d775bcc544
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWFlMWUwNjI2MTRiYTY0Y2RiMzcwYyIsImlhdCI6MTc0NjY1NjQxNywiZXhwIjoxNzQ2NjYwMDE3fQ.6vDDvUZ6USKJaKjO38al_qKSVAu_fMyN4EuQqd-GS4c

{
    "email": "Test3@test.com"
}

###

GET http://localhost:3000/api/shared/share-list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWFmNGRlNjhiMmZmMDI0YWEyODc2OCIsImlhdCI6MTc0NjY1NTUzOCwiZXhwIjoxNzQ2NjU5MTM4fQ.EtYFsidiM9y3gx30ROmnD2r9gE5kpAytpWOamkvBpm0

###

Post http://localhost:3000/api/shared/add-task-to-shared-list/681b17574c7fc7d775bcc544
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWFmNGRlNjhiMmZmMDI0YWEyODc2OCIsImlhdCI6MTc0NjY1NTUzOCwiZXhwIjoxNzQ2NjU5MTM4fQ.EtYFsidiM9y3gx30ROmnD2r9gE5kpAytpWOamkvBpm0

{
    "title": "Task2 from shared list",
    "description": "New Task from TestUser"
}